Hapi updated
adoptapanama/admin-api pull request #22
Opened 2018-03-26 21:27 UTC by AndresSp

i found a new version available for npm and hapi when i ran my enviroment

2018-03-26 22:45 UTC, fdvj commented
Please rebase your branch from develop like this
```
git checkout develop
git pull upstream develop
git checkout -
git rebase develop
git push -f
```

2018-03-27 03:55 UTC, AndresSp commented
but that didnt change anything 
![screenshot from 2018-03-26 22-45-11](https://user-images.githubusercontent.com/24443839/37946016-b1c585cc-3148-11e8-960c-ca841340d4c8.png)

2018-03-27 08:59 UTC, AndresSp commented
My origin and upstream were my forked repository lol, sorry

2018-03-27 09:24 UTC, AndresSp commented
How can i separate my last commit, for create a new PR? Well, i will change the title for this PR and include it

2018-03-27 12:20 UTC, fdvj requested changes
You are missing the tests. Ill merge this when the tests are included.

You can join commits by doing what is known as a squash. I can do it on merge if you like, or I can show you how to do it from the terminal

2018-03-27 12:20 UTC, fdvj commented on handlers/organizations.js
> +        const organizations = await this.models.organization.listOrganizations();
The model always begins with a capital letter. Here it will be `this.models.Organization.listOrganizations()`

2018-03-28 22:41 UTC, closed without merging